export type ContractAnnexCClause = {
  number: string;
  title: string;
  body: string[];
};

export const contractAnnexCClauses: ContractAnnexCClause[] = [
  {
    "number": "1",
    "title": "APPLICATION, INCORPORATION AND ORDER OF PRECEDENCE",
    "body": [
      "1.1 This Annex C forms an integral part of the Seafarer Employment Agreement and shall be read together with the Introductory Note and Annexes A, B and D.",
      "Collectively, the Introductory Note and Annexes A, B, C and D constitute the written Agreement between the Seafarer and the Employer, together with any supplementary Job Description, Yacht Rules, safety procedure, operational policy or other document validly communicated in accordance with this Annex C.",
      "1.2 This Agreement shall be interpreted and applied in accordance with all mandatory laws and regulations applicable to the employment relationship, the requirements of the Yacht’s flag State, the Maritime Labour Convention, 2006, as amended, where applicable, and any applicable collective bargaining agreement.",
      "Nothing in this Agreement shall exclude, restrict or reduce any mandatory right or protection granted to the Seafarer.",
      "1.3 In the event of any conflict or inconsistency, mandatory applicable law, the Yacht’s flag-State requirements and any applicable collective bargaining agreement shall prevail.",
      "Subject to the foregoing, the specific employment terms and Special Conditions expressly stated in Annex B shall prevail over any conflicting general provision of this Annex C.",
      "1.4 All provisions of this Annex C shall apply in full unless Annex B contains a written Special Condition that expressly supplements, varies or replaces a particular provision of this Annex C.",
      "A Special Condition shall prevail only to the extent of the specific matter or inconsistency addressed by it. All remaining provisions of Annex C shall continue in full force and effect.",
      "1.5 Any Special Condition intended to vary a provision of Annex C shall be clearly recorded in Annex B and accepted by the Seafarer and the Employer.",
      "A general, unclear or unrelated statement shall not be interpreted as excluding or reducing any provision of Annex C or any mandatory right of the Seafarer.",
      "1.6 Any Job Description, Yacht Rules, operational policy, safety procedure or instruction communicated separately under this Agreement shall supplement this Agreement but shall not, by itself, amend the Seafarer’s salary, position, leave entitlement, contract duration, notice period or other material employment terms.",
      "Any material change to such terms shall require the written or electronically recorded agreement of the Seafarer and the Employer."
    ]
  },
  {
    "number": "2",
    "title": "DUTIES, JOB DESCRIPTION AND GENERAL OBLIGATIONS OF THE SEAFARER",
    "body": [
      "2.1 The Seafarer shall perform the duties appropriate to their position, qualifications, competence and experience, as stated in Annex B and as further communicated in accordance with this Clause, with due skill, care, diligence and professionalism.",
      "2.2 The Seafarer shall comply with all lawful and reasonable instructions issued by the Master, Employer, Shipowner, Management Company or any duly authorised officer, provided that such instructions are consistent with applicable law, this Agreement and safe working practices.",
      "2.3 The Seafarer shall comply with all applicable laws and regulations, flag-State requirements, safety and security procedures, environmental-protection requirements, the Yacht’s safety-management procedures and all lawful and reasonable Yacht Rules communicated in accordance with Clause 9.",
      "2.4 The Seafarer shall take reasonable care of their own health and safety and that of all other persons on board.",
      "The Seafarer shall properly use any personal protective equipment provided and shall participate in all required safety training, emergency drills and familiarisation procedures.",
      "2.5 The Seafarer shall promptly report to the Master or appropriate senior officer any accident, injury, illness, unsafe condition, equipment defect, pollution incident, security concern or other matter that may affect the safe or lawful operation of the Yacht.",
      "2.6 The Seafarer shall exercise reasonable care in the use of the Yacht, its machinery, equipment, furnishings, documents and other property and shall not intentionally damage, misuse, remove or permit the unauthorised use of such property.",
      "2.7 Where reasonably required for the immediate safety of the Yacht, persons on board, the marine environment or another vessel or person in distress, the Seafarer shall assist with emergency duties outside their ordinary role, provided that the Seafarer is reasonably capable of performing such duties safely.",
      "2.8 The Seafarer shall comply with applicable working and rest-hour arrangements, maintain accurate records where required and promptly report any fatigue or circumstances that may impair their ability to perform their duties safely.",
      "2.9 Nothing in this Clause shall require the Seafarer to:",
      "(a) perform an unlawful or manifestly unsafe act;",
      "(b) waive any mandatory employment right; or",
      "(c) accept a permanent material change to their position, salary or other agreed employment terms without written agreement.",
      "2.10 The Seafarer shall hold and maintain throughout the period of employment all valid certificates, licences, endorsements, training records and other qualifications required for their position by applicable law, the Yacht’s flag State and any applicable international convention.",
      "The Seafarer shall promptly notify the Master and Employer of any expiry, suspension, restriction, withdrawal or loss affecting such documents.",
      "2.11 The Seafarer shall provide accurate copies of all required certificates and employment documents upon request and shall not knowingly submit any false, altered, expired or misleading document.",
      "2.12 The Seafarer may be required to perform reasonable duties ashore that are directly connected with the operation, maintenance, provisioning, administration or security of the Yacht, provided that such duties are appropriate to the Seafarer’s position, competence and safe working capacity.",
      "2.13 The Master, Employer, Shipowner or Management Company shall provide or make available to the Seafarer a Job Description appropriate to the Seafarer’s position.",
      "The Job Description may be communicated in writing, by email, through an approved electronic system or by another verifiable method.",
      "2.14 The Job Description may include the ordinary duties, responsibilities, reporting lines, watchkeeping obligations, guest-service duties, maintenance responsibilities, safety functions and other operational tasks reasonably associated with the Seafarer’s position.",
      "The assigned duties shall be appropriate to the Seafarer’s qualifications, competence, experience and ability to perform them safely.",
      "2.15 Once the Job Description has been reasonably communicated or made accessible, the Seafarer shall be responsible for familiarising themselves with it and performing the stated duties professionally and in accordance with this Agreement.",
      "Where requested, the Seafarer shall acknowledge receipt or access electronically or in writing. Failure to sign an acknowledgement shall not excuse non-compliance where the Job Description has otherwise been reasonably communicated and made available.",
      "2.16 The Seafarer may be assigned reasonable temporary, incidental or supporting duties that are directly related to the operation, maintenance, safety, security, provisioning or guest service of the Yacht, provided that such duties:",
      "(a) are reasonably connected with the Seafarer’s position or onboard service;",
      "(b) are within the Seafarer’s competence or can be performed safely with appropriate instruction; and",
      "(c) do not constitute a permanent material change to the agreed position or employment terms.",
      "2.17 Any material, recurring or permanent additional responsibility falling substantially outside the normal scope of the Seafarer’s position shall be discussed with the Seafarer and shall require the Seafarer’s written or electronically recorded acceptance before becoming a continuing contractual duty.",
      "Any related adjustment to position, salary, working arrangements or other material employment terms shall also be recorded in writing.",
      "2.18 Clauses 2.16 and 2.17 shall not prevent the Master from assigning reasonable emergency or safety-related duties outside the Seafarer’s ordinary position where immediately necessary to protect life, the Yacht, property or the marine environment."
    ]
  },
  {
    "number": "3",
    "title": "HOURS OF WORK, REST AND OPERATIONAL FLEXIBILITY",
    "body": [
      "3.1 Due to the nature of yacht operations, the Seafarer’s working hours may be irregular and may vary according to navigation schedules, guest requirements, arrivals and departures, mooring and anchoring operations, watchkeeping, maintenance, provisioning, weather conditions and the operational requirements of the Yacht.",
      "3.2 The Seafarer may be required to work flexible hours, split shifts, watches, nights, weekends and public holidays and may occasionally be required to work beyond their normal scheduled hours during busy operational periods.",
      "3.3 The Master shall organise working and rest periods as reasonably practicable, taking into account:",
      "(a) the safe operation of the Yacht;",
      "(b) the number of crew on board;",
      "(c) the Seafarer’s position and assigned duties; and",
      "(d) the operational demands prevailing at the relevant time.",
      "3.4 Except where a lawful exception applies, the Seafarer shall receive not less than:",
      "(a) ten (10) hours of rest in any twenty-four (24)-hour period; and",
      "(b) seventy-seven (77) hours of rest in any seven (7)-day period.",
      "Rest may be divided into no more than two periods, one of which shall be at least six (6) consecutive hours, and the interval between consecutive rest periods shall not exceed fourteen (14) hours.",
      "3.5 During particularly busy periods, including guest trips, charter operations, vessel movements, turnaround days, yard periods or other exceptional operational circumstances, normal working schedules may be temporarily adjusted.",
      "Any such adjustment shall be limited to what is reasonably necessary and shall remain subject to applicable law, flag-State requirements and any applicable collective bargaining agreement.",
      "3.6 Where a scheduled rest period is interrupted or reduced due to operational requirements, the Master shall arrange adequate compensatory rest as soon as reasonably practicable.",
      "Ordinary guest service or routine operational demands shall not be used to justify repeated or systematic breaches of mandatory rest-hour requirements.",
      "3.7 The Master may require the Seafarer to work any hours reasonably necessary for:",
      "(a) the immediate safety of the Yacht or persons on board;",
      "(b) the protection of the marine environment; or",
      "(c) assisting another vessel or person in distress.",
      "Once normal conditions have been restored, the Seafarer shall be provided with appropriate compensatory rest.",
      "3.8 Time spent on standby or on call shall be treated in accordance with applicable law.",
      "Where the Seafarer is required to perform work during a rest period, the time actually worked shall not be treated as rest, and adequate compensatory rest shall be provided.",
      "3.9 The Seafarer shall cooperate with the Yacht’s working and rest-hour arrangements, accurately record hours where required and promptly inform the Master where fatigue or insufficient rest may affect their ability to perform duties safely.",
      "3.10 Any entitlement to overtime payment, time off in lieu or additional compensation shall be governed by Annex B, applicable law and any applicable collective bargaining agreement."
    ]
  },
  {
    "number": "4",
    "title": "WAGES, PAYMENTS AND DEDUCTIONS",
    "body": [
      "4.1 The Seafarer’s basic wage, currency of payment, payment date and any agreed allowances, bonuses, overtime arrangements or other benefits shall be as stated in Annex B.",
      "4.2 Wages shall be paid regularly and in full at intervals not exceeding one month, by bank transfer to an account nominated by the Seafarer or by another lawful payment method agreed between the parties.",
      "4.3 Where the Seafarer commences or ends employment part-way through a month, wages shall be calculated on a pro-rata basis.",
      "The calculation method stated in Annex B or required by applicable law shall apply. Where neither specifies a method, the daily rate shall be calculated by multiplying the monthly basic wage by twelve (12) and dividing the resulting annual amount by three hundred and sixty-five (365).",
      "4.4 The Seafarer shall receive a monthly wage statement or other written payment record showing, as applicable:",
      "(a) the basic wage due;",
      "(b) any additional payments, allowances, bonuses or overtime;",
      "(c) any authorised deductions;",
      "(d) the net amount paid; and",
      "(e) the exchange rate used where payment is made in a different currency.",
      "4.5 No deduction shall be made from the Seafarer’s wages unless it is:",
      "(a) required or permitted by applicable law;",
      "(b) expressly authorised by this Agreement or Annex B; or",
      "(c) separately agreed in writing by the Seafarer.",
      "All deductions shall be reasonable, transparent, properly documented and clearly identified in the relevant wage statement.",
      "4.6 The Seafarer shall not be charged for ordinary wear and tear, operational losses, accidental breakage or damage arising during the proper performance of their duties.",
      "Any deduction relating to loss or damage caused by the Seafarer may only be made where permitted by applicable law and following a fair assessment of the circumstances, including whether the loss resulted from wilful misconduct, dishonesty or gross negligence.",
      "4.7 Bank charges imposed by the Employer’s sending bank shall be borne by the Employer.",
      "Any currency conversion shall be made using a reasonable and identifiable exchange rate, and no unreasonable administrative fee or exchange margin shall be imposed on the Seafarer.",
      "4.8 Any tips, guest gratuities, charter gratuities, discretionary bonuses or performance bonuses shall not form part of the Seafarer’s guaranteed basic wage unless expressly stated in Annex B.",
      "Where gratuities are received, they shall be distributed in accordance with the Yacht’s established gratuity policy or another arrangement communicated to the crew.",
      "4.9 Overtime payment, additional leave, time off in lieu or other compensation for additional working hours shall apply only where provided in Annex B, required by applicable law or separately agreed in writing.",
      "Nothing in this Clause shall permit working arrangements that breach the mandatory rest requirements set out in Clause 3.",
      "4.10 The Seafarer shall be responsible for personal tax declarations and liabilities that the Employer is not legally required to deduct or pay.",
      "Any tax, social-security, national-insurance, pension contribution or similar obligation legally imposed upon the Employer, Shipowner or Management Company shall remain their responsibility and shall not be transferred to the Seafarer.",
      "4.11 Upon termination or expiry of employment, all outstanding wages and other undisputed sums due to the Seafarer shall be calculated and paid within the period required by applicable law.",
      "Approved and properly documented expenses incurred on behalf of the Yacht shall be reimbursed separately and shall not be treated as wages.",
      "4.12 The Employer and/or Shipowner shall provide the Seafarer with reasonable means to remit all or part of their earnings to family members, dependants, legal beneficiaries or another nominated account.",
      "Any charges relating to such remittance shall be reasonable, and any currency conversion shall be made using a reasonable and identifiable exchange rate."
    ]
  },
  {
    "number": "5",
    "title": "ANNUAL LEAVE, ROTATION, SHORE LEAVE AND PUBLIC HOLIDAYS",
    "body": [
      "5.1 The Seafarer’s annual-leave entitlement, rotation arrangement and any additional leave benefits shall be as stated in Annex B and shall not be less than the minimum entitlement required by applicable law, flag-State requirements or any applicable collective bargaining agreement.",
      "5.2 Where the Maritime Labour Convention, 2006, as amended, applies, paid annual leave shall accrue at a rate of not less than two and one-half (2.5) calendar days for each completed month of employment, or on a pro-rata basis for an incomplete period of employment, unless a more favourable entitlement applies.",
      "5.3 Annual leave shall be taken at times agreed between the Seafarer and Employer, taking into account:",
      "(a) guest or charter schedules;",
      "(b) planned voyages, crossings and vessel movements;",
      "(c) yard, maintenance and refit periods;",
      "(d) the availability and safe manning of the Yacht;",
      "(e) the Seafarer’s position and departmental responsibilities; and",
      "(f) the reasonable personal circumstances of the Seafarer.",
      "Leave requests shall not be unreasonably refused or delayed.",
      "5.4 The Seafarer shall submit leave requests as early as reasonably practicable and shall not make non-refundable travel arrangements until the leave dates have been approved by the Master, Employer or Management Company.",
      "5.5 Due to the operational nature of the yachting industry, an approved or requested leave period may be postponed or rescheduled where reasonably necessary because of an unexpected guest trip, charter, voyage, crew shortage, technical emergency, yard delay or other significant operational requirement.",
      "The Seafarer shall be consulted, and alternative leave dates shall be arranged as soon as reasonably practicable without loss of accrued entitlement.",
      "5.6 Annual leave may be taken in one or more periods.",
      "Any division, postponement or carry-over of accrued leave shall be agreed between the parties and recorded where required.",
      "Accrued leave shall not be forfeited solely because operational circumstances, crew shortages, voyage planning or the Employer’s scheduling prevented it from being taken during the relevant leave year.",
      "5.7 Where the Seafarer works under a rotational or scheduled leave arrangement, Annex B shall clearly state:",
      "(a) the applicable rotation pattern;",
      "(b) whether the period ashore is paid or unpaid;",
      "(c) whether the period ashore includes accrued annual leave, compensatory leave or both; and",
      "(d) which party is responsible for related travel expenses.",
      "A scheduled period ashore shall not automatically be treated as annual leave unless expressly stated in Annex B.",
      "5.8 Public holidays may be worked where required by guest service, navigation, watchkeeping, safety, maintenance or other Yacht operations.",
      "Any entitlement to additional paid leave, compensatory leave or payment in respect of public holidays shall be governed by applicable law, flag-State requirements, any applicable collective bargaining agreement and Annex B.",
      "5.9 Temporary shore leave may be granted while the Yacht is in port where consistent with the Seafarer’s duties, safe-manning requirements, security arrangements, immigration restrictions and the Yacht’s operational schedule.",
      "Ordinary shore leave shall not be deducted from annual leave unless expressly requested by the Seafarer or otherwise permitted by applicable law.",
      "5.10 Sick leave, medically certified absence, required professional training, compensatory rest, maternity or parental leave and other legally protected or authorised absences shall not be treated as annual leave except where expressly permitted by applicable law and separately agreed with the Seafarer.",
      "5.11 During paid annual leave, the Seafarer shall continue to receive the basic wage and any guaranteed contractual payments required by Annex B or applicable law.",
      "Discretionary bonuses, gratuities and payments dependent upon active service on board shall not be payable during leave unless otherwise stated in Annex B.",
      "5.12 Travel for approved annual leave or rotation shall be handled in accordance with Annex B and Clause 7.",
      "5.13 The minimum paid annual-leave entitlement shall not be replaced by payment in lieu except upon termination of employment or where expressly permitted by applicable law.",
      "Upon termination, accrued but untaken annual leave shall be calculated and settled in accordance with applicable law and Annex B."
    ]
  },
  {
    "number": "6",
    "title": "MEDICAL FITNESS, INSURANCE AND MEDICAL CARE",
    "body": [
      "6.1 The Seafarer shall hold and maintain a valid medical-fitness certificate required by the Yacht’s flag State.",
      "6.2 The Seafarer shall promptly disclose any material illness, injury, medical restriction or use of medication that may reasonably affect their fitness for duty, the safe performance of their responsibilities or the health and safety of other persons on board.",
      "The Seafarer shall not be required to disclose private medical information that is unrelated to fitness for duty, onboard safety, insurance administration or another lawful employment purpose.",
      "6.3 Where the Seafarer becomes ill or injured during employment, the Employer and/or Shipowner shall ensure that prompt and appropriate medical care is made available in accordance with applicable law, the Yacht’s flag-State requirements and, where applicable, the Maritime Labour Convention, 2006, as amended.",
      "6.4 At their own cost, the Employer and/or Shipowner shall provide or arrange one or more of the following, provided that all mandatory medical-care, insurance, financial-security and compensation obligations are fully satisfied:",
      "(a) health, crew, P&I or other insurance or financial security accepted by the Yacht’s flag State;",
      "(b) suitable private health insurance covering the Seafarer and the Yacht’s intended cruising area;",
      "(c) full payment of the premium for suitable health or medical insurance arranged for the Seafarer; or",
      "(d) direct payment or prompt reimbursement of reasonable and necessary medical expenses, including medical consultations, hospital treatment, prescribed medicines, emergency transportation, medical evacuation and repatriation where required.",
      "6.5 The selected arrangement shall provide no less protection than required by applicable law, the Yacht’s flag State and, where applicable, the MLC.",
      "Where a particular form of insurance or financial security is legally required, payment of medical expenses or an insurance premium alone shall not replace that mandatory requirement.",
      "6.6 Insurance premiums and mandatory medical expenses shall not be deducted from the Seafarer’s wages.",
      "Upon reasonable request, the Seafarer shall be provided with evidence of the applicable insurance, financial security or medical coverage.",
      "6.7 Except in an emergency, the Seafarer shall obtain prior approval before arranging substantial private medical treatment at the Employer’s expense.",
      "Medical information shall be handled confidentially and disclosed only where reasonably necessary for treatment, determining fitness for duty, insurance administration or legal compliance.",
      "6.8 Where required by applicable law, the Yacht’s flag State or the MLC, the Employer and/or Shipowner shall maintain appropriate insurance or financial security for contractual compensation arising from employment-related death, permanent disability or long-term disability.",
      "Where required, documentary evidence of such financial security shall be carried aboard the Yacht and made reasonably accessible to the Seafarer.",
      "6.9 In the event of the Seafarer’s death during the period of employment, any mandatory burial, funeral or related expenses shall be met, and reasonable measures shall be taken to safeguard and return the Seafarer’s personal documents and property to their nominated representative or next of kin.",
      "6.10 Any social-security, pension, sickness, maternity, employment-injury, disability or other statutory protection applicable to the Seafarer shall be provided or administered in accordance with applicable law, the Yacht’s flag-State requirements and any applicable collective bargaining agreement.",
      "Details of coverage or benefits specifically provided by the Employer and/or Shipowner shall be stated in Annex B where required."
    ]
  },
  {
    "number": "7",
    "title": "TRAVEL, JOINING, LEAVE AND REPATRIATION",
    "body": [
      "7.1 The Employer and/or Shipowner shall arrange and pay for reasonable economy-class travel and necessary transfers required for the Seafarer to join the Yacht at the commencement of employment and to leave the Yacht upon expiry or termination of this Agreement.",
      "7.2 Travel for approved annual leave or an agreed rotation period shall be arranged and paid in accordance with Annex B.",
      "Where such travel is payable by the Employer and/or Shipowner, it shall include reasonable economy-class return travel and necessary airport, port or ground transfers between the Yacht and the agreed destination.",
      "7.3 All travel arrangements shall be approved and, where practicable, booked by the Employer, Shipowner or Management Company.",
      "Personal route changes, ticket upgrades, additional stops and excess baggage requested by the Seafarer shall be paid by the Seafarer unless otherwise approved or required by applicable law.",
      "7.4 The Seafarer shall be entitled to repatriation at the Employer’s and/or Shipowner’s cost where required by applicable law, the Yacht’s flag-State requirements and, where applicable, the Maritime Labour Convention, 2006, as amended.",
      "Repatriation shall be to the destination stated in Annex B or another destination mutually agreed in writing.",
      "7.5 Employer-paid travel and repatriation costs shall include, where reasonably necessary:",
      "(a) airfare or other transportation;",
      "(b) airport, port and ground transfers;",
      "(c) accommodation and meals during necessary travel;",
      "(d) reasonable baggage costs; and",
      "(e) essential medical assistance during travel.",
      "7.6 Joining, leave and repatriation expenses shall not be deducted from the Seafarer’s wages, annual-leave entitlement or other contractual payments.",
      "Recovery from the Seafarer may only occur where:",
      "(a) expressly permitted by applicable law, flag-State requirements or an applicable collective bargaining agreement; and",
      "(b) a serious breach of the Seafarer’s employment obligations has been properly and finally determined through a fair procedure.",
      "Any permitted recovery shall be limited to the amount and method permitted by law and shall be recorded in writing.",
      "7.7 The Seafarer shall be responsible for obtaining and maintaining a valid passport and for providing accurate information and completing any personal visa-application formalities required to accept the employment.",
      "The Employer and/or Shipowner shall not be obliged to guarantee the issuance or approval of any visa.",
      "Where required by applicable law, the Yacht’s flag State or the MLC, the cost of a visa required for the Seafarer’s employment, joining or service aboard the Yacht shall be borne by the Employer and/or Shipowner.",
      "Where the Seafarer’s visa or permitted period of stay expires while serving aboard the Yacht, the Employer and/or Shipowner shall arrange and pay for all reasonable agency charges, immigration formalities, exit permits and any necessary transit visa required for lawful departure or repatriation.",
      "This obligation shall not extend to additional costs resulting from false information, intentional concealment or failure by the Seafarer to cooperate with the required formalities.",
      "7.8 The Seafarer shall not be required to remain in continuous service aboard the Yacht beyond the maximum period permitted by applicable law, the Yacht’s flag State or any applicable collective bargaining agreement without being provided with the applicable leave or repatriation entitlement.",
      "7.9 Where required by applicable law, the Yacht’s flag State or the MLC, the Shipowner shall maintain appropriate financial security covering abandonment, repatriation, essential needs and outstanding wages and contractual entitlements.",
      "Where required, the certificate or other documentary evidence of such financial security shall be carried aboard the Yacht and made reasonably accessible to the Seafarer.",
      "The existence of such financial security shall not reduce any direct responsibility of the Employer or Shipowner.",
      "7.10 Where the Yacht is instructed to enter a warlike, armed-conflict or officially designated high-risk area, the Seafarer shall be informed as early as reasonably practicable.",
      "Any right to refuse such service, terminate the Agreement, receive additional protection or be repatriated shall be determined in accordance with applicable law, flag-State requirements, Annex B and any applicable collective bargaining agreement."
    ]
  },
  {
    "number": "8",
    "title": "ACCOMMODATION, MEALS AND LIVING CONDITIONS",
    "body": [
      "8.1 The Employer and/or Shipowner shall provide the Seafarer, without charge, with suitable accommodation, meals, drinking water and basic living facilities while serving aboard the Yacht, in accordance with applicable law, the Yacht’s flag-State requirements and, where applicable, the Maritime Labour Convention, 2006, as amended.",
      "8.2 Accommodation may consist of a private or shared crew cabin, depending on the Yacht’s design, available space, crew structure and operational requirements.",
      "The allocated accommodation shall be safe, clean, properly ventilated and reasonably suitable for rest.",
      "8.3 The Seafarer shall be provided with appropriate bedding, access to sanitary facilities and reasonable access to laundry facilities.",
      "The Seafarer shall keep their cabin and shared crew areas clean, orderly and hygienic.",
      "8.4 Adequate and nutritious meals shall be provided during the period of service on board.",
      "Reasonable efforts shall be made to accommodate medically necessary, religious or other dietary requirements notified by the Seafarer in advance, subject to availability and the operational circumstances of the Yacht.",
      "8.5 The Seafarer shall use the accommodation, furnishings, equipment and shared facilities responsibly and shall comply with the lawful and reasonable Yacht Rules communicated under Clause 9.",
      "The privacy, comfort and reasonable use of shared spaces by other persons on board shall be respected.",
      "8.6 Where accommodation or normal living facilities are temporarily affected by maintenance, repair, refit, emergency or other operational circumstances, the Employer and/or Shipowner shall take reasonable steps to provide suitable alternative arrangements where necessary and reasonably practicable."
    ]
  },
  {
    "number": "9",
    "title": "PROFESSIONAL CONDUCT, YACHT RULES, ZERO-TOLERANCE STANDARDS AND DISCIPLINE",
    "body": [
      "9.1 The Seafarer shall behave professionally, respectfully and responsibly toward the Owner, guests, Master, officers, crew members, contractors and all other persons encountered during the performance of their duties.",
      "9.2 Harassment, bullying, discrimination, sexual harassment, violence, threats, intimidation, abusive behaviour, retaliation or deliberate humiliation shall not be tolerated on board or in connection with the Seafarer’s employment.",
      "9.3 The possession, use, supply, transfer or distribution of illegal drugs or other prohibited substances is strictly forbidden and shall constitute a zero-tolerance breach.",
      "The Seafarer shall inform the Master where any prescribed or non-prescribed medication may affect their fitness for duty or the safe performance of their responsibilities.",
      "9.4 The Seafarer shall not be under the influence of alcohol, illegal drugs or any impairing substance while:",
      "(a) on duty or watch;",
      "(b) operating machinery, tenders, vehicles or watercraft;",
      "(c) participating in safety or security operations; or",
      "(d) reasonably expected to respond to an emergency.",
      "A serious breach of this requirement shall constitute a zero-tolerance breach. Alcohol consumption at any other time shall comply with applicable law, flag-State limits and the Yacht Rules.",
      "9.5 The Master may restrict or prohibit alcohol consumption on board where reasonably necessary for safety, security, guest operations, navigation or legal compliance.",
      "9.6 Smoking and vaping shall be permitted only in designated areas and in accordance with the Yacht Rules, fire-safety procedures and local regulations.",
      "9.7 The Seafarer shall not engage in conduct ashore that may reasonably endanger the Yacht, delay its operations, breach immigration or local laws, or cause serious damage to the reputation or legitimate interests of the Yacht, Employer or Shipowner.",
      "9.8 Any alleged breach of this Clause or the Yacht Rules shall be considered fairly and in accordance with applicable law, flag-State requirements and the Yacht’s applicable disciplinary procedure.",
      "A serious or repeated breach may result in a warning, suspension from duty, removal from the Yacht or termination of employment.",
      "A zero-tolerance breach may constitute serious misconduct and grounds for termination without notice where permitted by applicable law.",
      "9.9 The Seafarer shall not solicit or accept any undisclosed personal commission, fee, payment, gift, rebate or financial benefit from any supplier, contractor, broker, agent or other person doing business with the Yacht.",
      "Any discount, rebate, credit or benefit relating to Yacht expenditure shall be disclosed to the Master or Employer and applied for the benefit of the Yacht.",
      "9.10 The Seafarer shall promptly disclose any personal, financial or business interest that may create an actual or potential conflict with their duties or the legitimate interests of the Yacht, Employer or Shipowner.",
      "Reasonable personal gifts of nominal value may be accepted only where permitted by the Yacht Rules and where they do not influence, or appear to influence, a purchasing or operational decision.",
      "9.11 Where permitted by applicable law and reasonably justified by safety, security, suspected misconduct or the Yacht’s lawful alcohol and drug policy, the Employer, Shipowner or Master may require proportionate alcohol or drug testing, security screening or inspection.",
      "Any such measure shall be conducted with due regard to the Seafarer’s dignity, privacy, confidentiality and right to fair treatment.",
      "9.12 An inspection of a crew cabin or personal belongings shall only be conducted for a legitimate and reasonable purpose, in accordance with applicable law and, where practicable, in the presence of the Seafarer or another witness.",
      "9.13 Where the Employer requires a medical examination for an employment-related purpose, the reasonable cost shall be borne by the Employer.",
      "The opinion of an Employer-appointed medical practitioner shall not automatically be treated as final and binding where applicable law permits the Seafarer to obtain a reasonable second medical opinion.",
      "9.14 The Master, Employer, Shipowner or Management Company may issue, maintain and reasonably update Yacht Rules concerning onboard conduct, safety, security, uniforms, personal appearance, hygiene, accommodation, guest interaction, use of Yacht facilities, smoking, alcohol, communications, visitors, shore leave and other operational matters.",
      "9.15 Yacht Rules may be communicated in writing, by email, through an approved electronic system, in an onboard manual or by another verifiable method.",
      "The Seafarer shall be provided with reasonable access to the current Yacht Rules and shall be informed of any material amendment affecting their duties, conduct or responsibilities.",
      "9.16 Once the Yacht Rules have been reasonably communicated or made accessible, the Seafarer shall familiarise themselves with and comply with them.",
      "Where requested, the Seafarer shall acknowledge receipt or access electronically or in writing. Failure to sign an acknowledgement shall not excuse non-compliance where the rules have otherwise been reasonably communicated and made accessible.",
      "9.17 Yacht Rules shall be lawful, reasonable, proportionate, non-discriminatory and consistent with this Agreement, applicable law and safe working practices.",
      "Yacht Rules shall not be used to reduce or amend the Seafarer’s salary, annual leave, position, contract duration, notice period, mandatory rest entitlement or other material employment terms without written agreement.",
      "9.18 The following shall be treated as zero-tolerance conduct:",
      "(a) violence, assault, serious threats or deliberate intimidation;",
      "(b) sexual harassment, serious harassment, bullying or discriminatory abuse;",
      "(c) possession, use, supply or distribution of illegal drugs;",
      "(d) theft, fraud, deliberate dishonesty or falsification of documents;",
      "(e) being materially impaired by alcohol or drugs while on duty, on watch or responsible for safety;",
      "(f) deliberate or reckless conduct creating a serious risk to life, the Yacht, persons on board or the marine environment;",
      "(g) possession of an unauthorised weapon on board;",
      "(h) serious or deliberate breach of security, confidentiality or Owner and guest privacy;",
      "(i) retaliation against a person who has made a genuine complaint or safety report; and",
      "(j) deliberate refusal to comply with a lawful safety or emergency instruction.",
      "9.19 A zero-tolerance breach may constitute serious misconduct and may result in immediate removal from duty, disembarkation or termination without notice, subject to applicable law and, where reasonably practicable, a fair investigation and an opportunity for the Seafarer to respond.",
      "The designation of conduct as zero tolerance shall not remove any mandatory procedural right or protection available to the Seafarer.",
      "9.20 A breach of a Yacht Rule that is not designated as zero tolerance shall be dealt with according to its nature, seriousness, consequences and any previous warnings.",
      "Repeated breaches or continued failure to comply following a reasonable warning may constitute misconduct and may result in termination where permitted by applicable law."
    ]
  },
  {
    "number": "10",
    "title": "CONFIDENTIALITY, PRIVACY AND SOCIAL MEDIA",
    "body": [
      "10.1 The Seafarer shall keep confidential all non-public information obtained during employment concerning the Owner, guests, Yacht, Employer, Shipowner, Management Company, crew members or Yacht operations.",
      "10.2 Confidential information includes, without limitation:",
      "(a) personal and financial information;",
      "(b) private conversations;",
      "(c) photographs, videos and audio recordings;",
      "(d) documents and electronic records;",
      "(e) passwords and access details;",
      "(f) security arrangements;",
      "(g) the Yacht’s current or future location;",
      "(h) itineraries and guest movements; and",
      "(i) operational or technical information.",
      "10.3 The Seafarer shall not photograph, record, publish, transmit or share any image, video, audio recording or information relating to the Yacht, Owner, guests or persons on board without prior authorisation from the Master, Employer or other authorised person.",
      "This restriction applies to social media, messaging applications, websites and all other public or private digital platforms.",
      "10.4 The Seafarer shall not disclose the Yacht’s current or future location, cruising itinerary, security arrangements, guest identities or movements where such disclosure may affect privacy, safety or security.",
      "10.5 Permission to take or share photographs or information may be withdrawn at any time.",
      "Authorised content shall not be used for advertising, commercial promotion, media publication or personal publicity without separate approval.",
      "10.6 Nothing in this Clause shall prevent the Seafarer from:",
      "(a) performing their lawful duties;",
      "(b) obtaining confidential medical or legal advice;",
      "(c) reporting an accident, safety concern, harassment, discrimination, unlawful conduct or suspected regulatory breach;",
      "(d) making a lawful complaint under the Yacht’s complaint procedure; or",
      "(e) providing information to an authorised authority where required or permitted by law.",
      "10.7 The Seafarer shall take reasonable care of passwords, electronic devices, access cards, documents and personal data entrusted to them and shall promptly report any loss, unauthorised access or suspected data breach.",
      "10.8 Upon termination of employment, the Seafarer shall return all Yacht property, documents, access credentials and confidential records and shall delete unauthorised copies held on personal devices or accounts.",
      "The Seafarer may retain personal employment documents, including this Agreement, wage statements, medical records and professional certificates.",
      "10.9 The Employer and/or Shipowner shall handle the Seafarer’s personal information confidentially and in accordance with applicable data-protection laws.",
      "Personal information may be disclosed only where reasonably necessary for employment administration, payroll, medical care, insurance, travel, security, regulatory compliance or legal obligations.",
      "10.10 The obligations under this Clause shall continue after termination of employment for as long as the relevant information remains confidential.",
      "10.11 Where the Seafarer signs a separate confidentiality or non-disclosure agreement, that agreement shall be read together with this Clause and shall not restrict the protected disclosures and rights set out in Clause 10.6 or Clause 12."
    ]
  },
  {
    "number": "11",
    "title": "SAFETY, SECURITY AND ENVIRONMENTAL PROTECTION",
    "body": [
      "11.1 The Seafarer shall comply with all applicable safety, security and environmental requirements, flag-State regulations, onboard procedures, Yacht Rules communicated under Clause 9 and all lawful instructions issued by the Master or authorised officers.",
      "11.2 The Seafarer shall complete all required safety familiarisation, training and emergency drills and shall become familiar with:",
      "(a) alarm signals;",
      "(b) muster stations;",
      "(c) escape routes;",
      "(d) lifesaving appliances;",
      "(e) firefighting equipment; and",
      "(f) their assigned emergency duties.",
      "11.3 The Seafarer shall use all required personal protective equipment, tools and machinery safely and shall follow applicable risk assessments, permits to work and safe-working procedures.",
      "No safety device shall be removed, disabled or bypassed without proper authorisation.",
      "11.4 The Seafarer shall promptly report any accident, injury, near miss, unsafe condition, equipment defect, security concern, pollution incident or other matter that may affect the Yacht, persons on board or the marine environment.",
      "11.5 The Seafarer shall not operate machinery, tenders, watercraft, vehicles or technical equipment unless properly trained, competent and authorised to do so.",
      "11.6 The Seafarer shall comply with all waste-management, sewage, fuel, oil, chemical and pollution-prevention procedures.",
      "No waste, pollutant or other material shall be discharged into the sea except where expressly permitted by applicable law and authorised onboard procedures.",
      "11.7 The Seafarer shall comply with the Yacht’s security arrangements, including access control, visitor procedures and the protection of keys, access cards, security codes and restricted areas.",
      "Any suspicious activity, unauthorised person or security breach shall be reported immediately.",
      "11.8 In an emergency, the Seafarer may be required to perform reasonable duties outside their normal position where necessary to protect life, the Yacht, property or the environment, provided that they are reasonably capable of carrying out such duties safely.",
      "11.9 The Employer and/or Shipowner shall take reasonable measures to provide a safe working environment, properly maintained equipment, necessary safety training and suitable personal protective equipment in accordance with applicable law, flag-State requirements and, where applicable, the MLC."
    ]
  },
  {
    "number": "12",
    "title": "COMPLAINTS, GRIEVANCES, DISPUTES AND PROTECTION AGAINST RETALIATION",
    "body": [
      "12.1 The Seafarer may raise a complaint or grievance concerning wages, working or living conditions, safety, discrimination, harassment, treatment on board, rest hours, privacy or any alleged breach of this Agreement, applicable law or the Yacht Rules.",
      "12.2 Where reasonably practicable, the Seafarer should first raise the matter with their immediate supervisor or Head of Department.",
      "If the matter is not resolved, the complaint may be referred to the Master and thereafter to the Employer, Shipowner or Management Company.",
      "12.3 Where the complaint concerns the Seafarer’s supervisor, Head of Department or Master, or involves an urgent or serious safety, medical, harassment, discrimination, retaliation or unlawful-conduct concern, the Seafarer may bypass the normal reporting steps and contact the Employer, Shipowner, Management Company or an appropriate external authority directly.",
      "12.4 Complaints shall be handled promptly, fairly, confidentially and, where appropriate, recorded in writing.",
      "The persons involved shall be given a reasonable opportunity to provide relevant information and respond to the complaint.",
      "12.5 The Seafarer shall have the right to be accompanied or represented during the complaint procedure by another crew member or other permitted representative.",
      "12.6 No Seafarer shall be dismissed, threatened, disadvantaged, harassed or otherwise subjected to retaliation for:",
      "(a) making a genuine complaint in good faith;",
      "(b) assisting another Seafarer; or",
      "(c) reporting a safety, legal or regulatory concern.",
      "12.7 Nothing in this Agreement shall prevent the Seafarer from contacting a flag-State authority, port-State authority, seafarers’ representative, legal adviser or other competent authority where permitted by law.",
      "12.8 Where required by applicable law, the Yacht’s flag State or the MLC, the Seafarer shall be provided with access to the applicable onboard complaint procedure and relevant contact details.",
      "12.9 A complaint made honestly and in good faith shall not be treated as misconduct merely because it is not upheld.",
      "Knowingly providing false information or making a deliberately malicious complaint may be addressed under the applicable disciplinary procedure.",
      "12.10 The parties shall first attempt to resolve employment-related disputes fairly and in good faith through the procedures set out in this Clause, except where urgent legal or protective action is reasonably required.",
      "12.11 Where a dispute cannot be resolved internally, it may be submitted to a competent court, tribunal, flag-State authority, port-State authority or other body having jurisdiction under applicable law.",
      "12.12 Nothing in this Agreement shall restrict a mandatory right of the Seafarer to seek legal advice, contact a competent authority, commence lawful proceedings or pursue another legally available remedy."
    ]
  },
  {
    "number": "13",
    "title": "TERMINATION OF EMPLOYMENT",
    "body": [
      "13.1 This Agreement may end upon:",
      "(a) expiry of the agreed contract period;",
      "(b) completion of an agreed voyage;",
      "(c) mutual written agreement;",
      "(d) termination by either party with notice; or",
      "(e) lawful termination without notice.",
      "13.2 Either party may terminate this Agreement by giving the written notice stated in Annex B.",
      "The notice period shall comply with applicable law, flag-State requirements and any applicable collective bargaining agreement.",
      "Where the MLC applies, the minimum notice period shall not be less than seven (7) days, and the notice required from the Employer or Shipowner shall not be shorter than that required from the Seafarer.",
      "A shorter notice period or termination without notice may apply only where permitted by applicable law, regulation or an applicable collective bargaining agreement.",
      "13.3 Where a trial period applies, Annex B shall separately state:",
      "(a) the length of the trial period;",
      "(b) the notice period during the trial period; and",
      "(c) the notice period after successful completion of the trial period.",
      "Either party may terminate during the trial period by giving the notice stated in Annex B, subject to applicable law and flag-State requirements.",
      "13.4 Successful completion of the trial period shall not create a new employment agreement unless expressly stated in Annex B.",
      "13.5 The Employer and/or Shipowner may terminate the Agreement for genuine operational reasons, including:",
      "(a) sale or loss of the Yacht;",
      "(b) lay-up or extended refit;",
      "(c) change of ownership or management;",
      "(d) reduction of crew or redundancy of the position; or",
      "(e) circumstances preventing continued operation of the Yacht.",
      "The Seafarer shall remain entitled to outstanding contractual and mandatory payments and, where applicable, repatriation.",
      "13.6 The Employer and/or Shipowner may terminate without notice where permitted by applicable law in cases of:",
      "(a) serious misconduct;",
      "(b) a sufficiently serious zero-tolerance breach under Clause 9.18;",
      "(c) gross negligence;",
      "(d) dishonesty or theft;",
      "(e) violence or serious harassment;",
      "(f) illegal drug possession, use or distribution;",
      "(g) serious safety or security violations;",
      "(h) deliberate disobedience of lawful orders;",
      "(i) falsification of certificates or employment documents; or",
      "(j) another serious or fundamental breach of this Agreement.",
      "Where reasonably practicable, the matter shall be investigated fairly and the Seafarer shall be given an opportunity to respond.",
      "13.7 The Seafarer may terminate on shorter notice or without notice where permitted by applicable law due to:",
      "(a) serious or repeated non-payment of wages;",
      "(b) unsafe working conditions;",
      "(c) harassment, discrimination or abuse;",
      "(d) a material breach by the Employer or Shipowner;",
      "(e) medical incapacity;",
      "(f) compassionate or urgent circumstances; or",
      "(g) another lawful and justified reason.",
      "13.8 Notice of termination shall be given in writing and shall state the intended termination date.",
      "During the notice period, the Seafarer shall continue to perform their duties professionally and complete a reasonable handover unless relieved from duty.",
      "Payment in lieu of notice may be made where permitted by applicable law.",
      "13.9 Following notice, the Employer may relieve the Seafarer from some or all duties where reasonably necessary for safety, security, confidentiality, operational continuity or orderly handover.",
      "Unless otherwise permitted by applicable law, the Seafarer shall continue to receive their basic wage and guaranteed contractual benefits during an Employer-directed suspension forming part of the notice period.",
      "13.10 Where the notice period expires while the Yacht is at sea, or where safe and lawful disembarkation is not reasonably possible, employment shall continue until arrival at the next suitable port or another agreed place of discharge.",
      "Wages and applicable benefits shall continue until the Seafarer is lawfully discharged.",
      "13.11 Upon termination, the Seafarer shall be paid all outstanding wages, accrued but untaken annual leave, approved expenses and other undisputed contractual entitlements within the period required by applicable law.",
      "Any deduction shall be lawful, reasonable, documented and clearly recorded.",
      "13.12 Travel or repatriation following termination shall be arranged in accordance with Clause 7, applicable law, flag-State requirements and, where applicable, the MLC.",
      "13.13 Before leaving the Yacht, the Seafarer shall return all Yacht property, keys, uniforms, equipment, documents and access credentials in their possession.",
      "The Employer shall return the Seafarer’s personal documents and provide a record of employment where required by law.",
      "13.14 Where the Seafarer is held captive on or off the Yacht as a result of piracy or armed robbery against ships, this Agreement shall continue in effect and wages and other applicable contractual entitlements shall continue to be paid as required by applicable law and, where applicable, the MLC, until the Seafarer is released and duly repatriated.",
      "Where the Seafarer dies while in captivity, wages and applicable contractual entitlements shall continue until the date of death determined in accordance with applicable law.",
      "13.15 Where this Agreement ends as a direct result of the loss, foundering, constructive total loss or permanent abandonment of the Yacht, the Seafarer shall remain entitled to:",
      "(a) outstanding wages;",
      "(b) accrued leave;",
      "(c) approved expenses;",
      "(d) repatriation; and",
      "(e) any unemployment indemnity or other compensation required by applicable law, flag-State requirements or the MLC.",
      "13.16 The Employer and/or Shipowner shall arrange and pay for repatriation following the loss or foundering of the Yacht in accordance with Clause 7.",
      "13.17 Where the Seafarer’s reasonable personal property is lost or damaged as a direct result of the loss or foundering of the Yacht, compensation shall be provided to the extent required by applicable law, flag-State requirements, any applicable collective bargaining agreement or the Yacht’s applicable insurance policy.",
      "13.18 The Seafarer shall provide reasonable details and, where available, supporting evidence of a personal-property claim.",
      "Compensation shall not normally apply to prohibited property, losses caused by intentional misconduct or undeclared high-value items where prior declaration was reasonably required.",
      "13.19 Nothing in this Clause shall restrict or reduce any greater compensation, insurance benefit or other right available under applicable law, insurance or an applicable collective bargaining agreement."
    ]
  },
  {
    "number": "14",
    "title": "GOVERNING LAW, JURISDICTION AND GENERAL PROVISIONS",
    "body": [
      "14.1 Governing Law",
      "14.1 Subject to applicable mandatory law, this Agreement shall be governed by and interpreted in accordance with the governing law stated in Annex B.",
      "Where no governing law is stated in Annex B, the Agreement shall be governed by the laws and regulations of the Yacht’s flag State.",
      "14.2 Mandatory Protections",
      "14.2 The selection of governing law shall not exclude, restrict or reduce:",
      "(a) any mandatory protection applicable under the law of the Yacht’s flag State;",
      "(b) any mandatory law applicable to the employment relationship;",
      "(c) any right arising under the Maritime Labour Convention, 2006, as amended, where applicable; or",
      "(d) any applicable collective bargaining agreement.",
      "14.3 Jurisdiction and Dispute Forum",
      "14.3 Any jurisdiction or dispute forum expressly stated in Annex B shall apply only to the extent permitted by applicable law.",
      "Where Annex B does not identify a jurisdiction or forum, a dispute may be brought before any court, tribunal, maritime authority, employment authority or other body having lawful jurisdiction.",
      "No exclusive-jurisdiction provision shall prevent the Seafarer from exercising a mandatory right to contact or commence proceedings before a competent authority.",
      "14.4 Entire Agreement",
      "14.4 This Agreement, consisting of the Introductory Note and Annexes A, B, C and D, constitutes the entire written agreement between the Seafarer and Employer concerning the employment covered by it and supersedes previous agreements, promises, arrangements or understandings relating to the same employment, except for:",
      "(a) any mandatory right that cannot lawfully be excluded;",
      "(b) any applicable collective bargaining agreement; and",
      "(c) any Job Description, Yacht Rules, safety procedure, operational policy or other document validly communicated in accordance with this Agreement.",
      "A Job Description, Yacht Rule, safety procedure, operational policy or other operational document shall not amend a material employment term unless the amendment is separately accepted in writing or by another legally valid electronic method.",
      "14.5 Amendments and Variations",
      "14.5 No amendment, variation, waiver, supplement or replacement of this Agreement shall be valid unless recorded in writing and accepted by the Seafarer and Employer or their duly authorised representatives.",
      "A change to the Yacht Rules, Job Description or onboard procedures shall not, by itself, amend a material employment term.",
      "14.6 Severability",
      "14.6 If any provision is found to be unlawful, invalid or unenforceable, it shall be applied to the maximum extent legally permitted or, where necessary, treated as severed.",
      "The remaining provisions shall continue in full force and effect.",
      "14.7 No Waiver",
      "14.7 A failure or delay by either party to exercise a right under this Agreement shall not constitute a permanent waiver of that right.",
      "A waiver relating to one event shall not automatically apply to a later event.",
      "14.8 Written Notices",
      "14.8 A notice required under this Agreement shall be given in writing.",
      "Notice may be delivered personally, by email, through an approved electronic-contract platform or by another verifiable electronic method using the contact details stated in Annex A or Annex B.",
      "Each party shall promptly notify the other of any relevant change to their contact details.",
      "14.9 Electronic Signatures and Counterparts",
      "14.9 This Agreement may be signed electronically and in separate counterparts.",
      "Each signed counterpart shall be treated as an original, and all counterparts together shall constitute the same Agreement, to the extent permitted by applicable law.",
      "14.10 Review, Advice and Signed Copy",
      "14.10 Before signing, the Seafarer shall be given a reasonable opportunity to review the Introductory Note and all Annexes, ask questions and seek independent advice.",
      "The Seafarer and Employer shall each receive or have continuing access to a complete signed copy of the Introductory Note and Annexes A, B, C and D.",
      "14.11 Place and Date of Agreement",
      "14.11 The place and date on which this Agreement is entered into shall be recorded in Annex D.",
      "Where the parties sign on different dates, the Agreement shall be regarded as executed on the date of the final signature unless another effective date is expressly stated in Annex B."
    ]
  }
];

export function getContractAnnexCLines() {
  return contractAnnexCClauses.flatMap((clause) => [
    `${clause.number}. ${clause.title}`,
    ...clause.body,
    "",
  ]);
}
