import type { GuideLanguage } from "./guide-index";

const english = {
  home: "Home",
  allArticles: "All articles",
  readArticle: "Read article",
  minutes: "min read",
  homeTitle: "Your next step starts",
  homeTitleAccent: "with the right knowledge.",
  homeDescription: "From your first application to your first day on board.",
  homeDescriptionEnd: "Practical insights for your yachting career.",
  homeFooter: "CREATED FOR CREW. FOR LIFE AT SEA.",
  career: "Career",
  cvProfile: "CV & profile",
  onboardLife: "Life on board",
  all: "All",
  breadcrumb: "Breadcrumb",
  libraryTitle: "For your career at sea,",
  libraryTitleAccent: "look a little further ahead.",
  libraryDescription: "A strong start begins with thoughtful preparation. Explore articles on sharing your experience,",
  libraryDescriptionEnd: "finding opportunities and settling into life on board.",
  categories: "Blog categories",
  search: "Search articles",
  clearSearch: "Clear search",
  emptyTitle: "No articles match your search.",
  emptyDescription: "Try a different search or explore all articles.",
  showAll: "Show all articles",
  libraryCtaEyebrow: "TURN KNOWLEDGE INTO YOUR NEXT STEP",
  libraryCtaTitle: "When you’re ready,",
  libraryCtaTitleEnd: "new opportunities await.",
  exploreJobs: "Explore open positions",
  articleCaption: "Perspectives on yachting careers and life on board.",
  inArticle: "IN THIS ARTICLE",
  tableOfContents: "Article contents",
  checklist: "Checklist",
  sidebarNote: "A strong start begins",
  sidebarNoteEnd: "with small, thoughtful steps.",
  backToArticles: "Back to all articles",
  atAGlance: "AT A GLANCE",
  chapter: "CHAPTER",
  nextStep: "YOUR NEXT STEP",
  authorDescription: "Practical insights to help you make informed decisions in your yachting career.",
  keepReading: "KEEP READING",
  nextArticle: "Your next read.",
  checklistEyebrow: "YOUR TURN",
  checklistTitle: "A quick checklist",
  checklistDescription: "Check off what’s ready and make your next step clear.",
  checklistDone: "You’re ready to take the next step.",
  carousel: "carousel",
  slide: "slide",
  previousArticle: "Previous article",
  nextArticleControl: "Next article",
};

type BlogCopy = typeof english;

const turkish: BlogCopy = {
  home: "Ana sayfa",
  allArticles: "Tüm yazılar",
  readArticle: "Yazıyı oku",
  minutes: "dk okuma",
  homeTitle: "Bir sonraki adımın,",
  homeTitleAccent: "doğru bilgiyle başlar.",
  homeDescription: "İlk başvurudan teknedeki ilk güne.",
  homeDescriptionEnd: "Yat kariyerine eşlik eden pratik bilgiler.",
  homeFooter: "CREW İÇİN HAZIRLANDI. DENİZDEKİ HAYAT İÇİN.",
  career: "Kariyer",
  cvProfile: "CV & Profil",
  onboardLife: "Teknede yaşam",
  all: "Tümü",
  breadcrumb: "Sayfa yolu",
  libraryTitle: "Denizdeki kariyerin için",
  libraryTitleAccent: "biraz daha ileriye bak.",
  libraryDescription: "İyi bir başlangıç, doğru hazırlıkla gelir. Deneyimini anlatmak,",
  libraryDescriptionEnd: "fırsatları değerlendirmek ve teknedeki hayata uyum sağlamak için yazılar.",
  categories: "Blog kategorileri",
  search: "Yazılarda ara",
  clearSearch: "Aramayı temizle",
  emptyTitle: "Bu aramayla eşleşen yazı bulunamadı.",
  emptyDescription: "Başka bir kelime deneyebilir veya tüm yazılara dönebilirsin.",
  showAll: "Tüm yazıları göster",
  libraryCtaEyebrow: "BİLGİDEN BİR SONRAKİ ADIMA",
  libraryCtaTitle: "Hazır olduğunda,",
  libraryCtaTitleEnd: "yeni fırsatlar seni bekliyor.",
  exploreJobs: "Açık ilanları keşfet",
  articleCaption: "Yat kariyeri ve teknedeki yaşam üzerine.",
  inArticle: "BU YAZIDA",
  tableOfContents: "Yazı içindekiler",
  checklist: "Kontrol listesi",
  sidebarNote: "İyi bir başlangıç,",
  sidebarNoteEnd: "küçük ve doğru adımlarla.",
  backToArticles: "Tüm yazılara dön",
  atAGlance: "BİR BAKIŞTA",
  chapter: "BÖLÜM",
  nextStep: "BİR SONRAKİ ADIM",
  authorDescription: "Yat kariyerinde daha bilinçli adımlar atman için pratik bilgiler.",
  keepReading: "OKUMAYA DEVAM ET",
  nextArticle: "Bir sonraki yazın.",
  checklistEyebrow: "SIRA SENDE",
  checklistTitle: "Kısa kontrol listesi",
  checklistDescription: "Hazır olanları işaretle, bir sonraki adımını netleştir.",
  checklistDone: "Hazırlık tamam. Bir sonraki adıma geçebilirsin.",
  carousel: "karusel",
  slide: "slayt",
  previousArticle: "Önceki yazı",
  nextArticleControl: "Sonraki yazı",
};

export function getBlogCopy(language: GuideLanguage) {
  return language === "tr" ? turkish : english;
}

export function articleCount(count: number, language: GuideLanguage) {
  return language === "tr" ? `${count} yazı` : `${count} ${count === 1 ? "article" : "articles"}`;
}

export function slidePosition(position: number, count: number, language: GuideLanguage) {
  return language === "tr" ? `${count} yazıdan ${position}. yazı` : `Article ${position} of ${count}`;
}
